src-git packages https://github.com/immortalwrt/packages.git;openwrt-24.10
src-git routing https://github.com/immortalwrt/routing.git;openwrt-24.10
src-git telephony https://github.com/immortalwrt/telephony.git;openwrt-24.10
src-git video https://github.com/immortalwrt/video.git;openwrt-24.10
src-git management https://github.com/immortalwrt/management.git;openwrt-24.10
